version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: ridify
    environment:
      POSTGRES_DB: ridify
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2445
    ports:
      - "5432"

    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: rentthis-app
    ports:
      - "8080"

    depends_on:
      - postgres

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ridify
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 2445


